#!/bin/bash
# =============================================================================
# MatrixChat Stage-2 data DOWNLOAD (run on an internet-capable node).
#
# Rosie compute nodes generally have NO internet, so run this on a login /
# transfer node. It populates the HF cache + GitHub clones under $RAW_DIR on the
# shared /data mount, so later (offline) jobs can read it from any node.
#
# Usage:
#   bash scripts/data_prep/download_data.sh
# =============================================================================
set -euo pipefail

# ---- Paths (edit location as needed) ----------------------------------------
# Default to $HOME (writable, mounted on all nodes). $USER contains an @domain on
# Rosie and /data is group-organized (no per-user dir), so $HOME is the safe
# default. To use the shared /data pool instead, e.g.:
#   export RAW_DIR=/data/ai_club/$(whoami | cut -d@ -f1)/matrixchat/raw
RAW_DIR="${RAW_DIR:-$HOME/matrixchat/raw}"
export HF_HOME="$RAW_DIR"
SOURCES="${SOURCES:-molweni meld ami werewolf conversation_chronicles}"
# werewolf's AdapterSpec restricts its snapshot to json/txt/md (skips ~9.9GB
# of video/audio in the source repo that this adapter never reads).

echo "host:    $(hostname)"
echo "RAW_DIR: $RAW_DIR"
echo "HF_HOME: $HF_HOME"
mkdir -p "$RAW_DIR"

python -m data.build_dataset --mode download \
  --sources $SOURCES \
  --raw_dir "$RAW_DIR"

echo "done. For offline preprocessing set: export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1"
echo "NOTE: the 'qwen_distill' source is generated by scripts/data_prep/distill_qwen.sbatch, not downloaded."
